### ISSUE TITLE
Checkboxes in UITableViewCell Objects

### ISSUE THREAD

**Issue by mbrahimi617** [Boris-Em/BEMCheckBox#81]
So I'm creating a questionnaire app in which I have a UITableView with a custom Cell class that inherits from UITableViewCell, and it contains an additional checkbox attribute on top of the inherited ones. My problem is twofold. 

Firstly, for whatever reason, the checkboxes will not render in the XCode interface builder. I'm running the latest versions of Swift and Xcode, and I installed via CocoaPods. Secondly, when the controller starts up some of the checkboxes are selected while others are not. As I scroll, some of them even change. Do you have any ideas as to what might be causing this?

**Comment by mbrahimi617** [comment]
Bear in mind that for a smaller number of cells such that all fit on the view without the need to scroll, I have absolutely no issue with the checkbox operations. I'm still unable to render them on the interface builder but everything works as expected.

**Comment by chejarla-venkatesh** [comment]
Sir, have found any solution for this. I don't know to record a touch event in UITableViews or UICollectionViews..

**Comment by mbrahimi617** [comment]
So I found some Podfile snippet to fix the issue with storyboards, however, I'm still facing the issues with checkboxes that change during scrolling. Any ideas why they're changing state while the UITableView scrolls?

**Comment by chejarla-venkatesh** [comment]
CheckBoxes are changing state because the TableView/CollectionView delegate method cellForRow/ItemAtIndexPath is called every time you scroll and as we use cells dequeue reusable property to create cells everyTime you scroll. So, new cells will be created for the part of the screen that is visible for your eye.

Explanation:
1. Let say that the checkBox for every cell is in unchecked state for the first time the TableView loads
2. When we changed the state of two checkBoxes to checked state
3. Now if we scroll down the TableView the cells which you have seen the before will be removed and new cell are created for the part of the TableView which you can actually see (we have to keep in mind that the cells for which we have checked the checkBoxes and all the cells which we have seen before scrolling down no longer exist)
4. Again we will change the state of the checkBox to checked for whichever cells you want and you scrolled the tableView to top the checkBoxes which you have checked before are not checked because they are the new cells and not the cells you have seen before
5. And even if you scroll down again all cells are back to their normal state bcoz they are the new cells.

I hope this explanation helps you to understand why the state of the checkBoxes are changing when scrolling.
 You can also check this by putting a breakpoint in the delegate method cellForRow/ItemAtIndexPath..

**Comment by mbrahimi617** [comment]
@chejarla-venkatesh Ah I see what you're saying. So do you have any work around?

**Comment by mbrahimi617** [comment]
Probably best to keep an array or hashmap and check state, although it would be a bit cumbersome.

**Comment by chejarla-venkatesh** [comment]
@mbrahimi617 Yes, but it is not so difficult to keep track of them. We have to create an array to store the checked cell indices and when we check a checkBox append the cell Index to the array and if we uncheck remove the index from the array and in the `cellForRow/ItemAtIndexPath` implement an if condition `if selectedCellIndex.contains(indexPath.item) {
            cell.selectCertificate.on = true
        } else {
            cell.selectCertificate.on = false
        }
        cell.selectCertificate.tag = indexPath.item`
